server:
  port: 8004
  servlet:
    context-path: /
spring:
  application:
    name: ThinkGearReader
  main:
    allow-bean-definition-overriding: true

thinkGearConnector:
  port: 13854
  host: "127.0.0.1"
  format: Json
  raw: true
  authMessage: "{\"appName\":\"%s\",\"appKey\":\"%s\"}\n"
  switchMessage: "{\"enableRawOutput\":%s,\"format\":\"%s\"}\n"

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  # static properties
  app:
    name: ${spring.application.name}
    description: --

logging:
  level:
    root: info
    com.globant.brainwaves.adapter: info
